project_id = "atgrxqfxysvppqoyvjdd"

[functions.generate-listing]
verify_jwt = false

[functions.append-to-sheet]
verify_jwt = false

[functions.refine-listing]
verify_jwt = false
 
 [functions.enhance-image]
 verify_jwt = false

[functions.generate-images-zip]
verify_jwt = false

[functions.ebay-publish]
verify_jwt = false

[functions.zapier-proxy]
verify_jwt = false

[functions.enrich-ebay-batch]
verify_jwt = false

[functions.ebay-oauth]
verify_jwt = false

[functions.generate-denver-listing]
verify_jwt = false

[functions.trigger-doa-agent]
verify_jwt = false

[functions.etsy-publish]
verify_jwt = false

[functions.reformat-listing]
verify_jwt = false

[functions.suggest-ebay-category]
verify_jwt = false

[functions.sync-ebay-categories]
verify_jwt = false

[functions.trigger-estatesales-agent]
verify_jwt = false

[functions.ebay-category-aspects]
verify_jwt = false
